In [52]:
import os
if os.getcwd().endswith("notebooks"):
    os.chdir('..')

print("Current working directory: ", os.getcwd())
if not os.getcwd().endswith("California-Housing-ML"):
    raise ValueError("Please change working directory to 'path/toCalifornia-Housing-ML' before proceeding")
!pip install -r requirements.txt

Current working directory:  /Users/irellzane/MLprojects/California-Housing-ML


In [67]:
import pandas as pd
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.cluster import KMeans
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import FunctionTransformer, StandardScaler, OneHotEncoder
from sklearn.metrics.pairwise import rbf_kernel
from sklearn.compose import ColumnTransformer, make_column_selector


class ClusterSimilarity(BaseEstimator, TransformerMixin):
    def __init__(self, n_clusters=10, gamma=1, random_state=None):
        self.n_clusters = n_clusters
        self.gamma = gamma
        self.random_state = random_state

    def fit(self, X, y=None, sample_weight=None):
        self.kmeans = KMeans(n_clusters=self.n_clusters, 
                             random_state=self.random_state)
        self.kmeans.fit(X, sample_weight=sample_weight)
        return self
    
    def transform(self, X):
        self.cluster_centers_ = self.kmeans.cluster_centers_
        return rbf_kernel(X, self.kmeans.cluster_centers_, gamma=self.gamma)
    
    def get_feature_names_out(self, names=None):
        return [f"Cluster {i} similarity" for i in range(self.n_clusters)]

def column_ratio(X):
    return X[:, [0]] / X[:, [1]]

def ratio_name(function_transformer, feature_names_in):
    return ["ratio"]

def ratio_pipeline():
    return make_pipeline(
        SimpleImputer(strategy="median"),
        FunctionTransformer(column_ratio, feature_names_out=ratio_name),
        StandardScaler()
    )

cat_pipeline = make_pipeline(SimpleImputer(strategy="most_frequent"),
                             OneHotEncoder(handle_unknown="ignore"))

log_pipeline = make_pipeline(
        SimpleImputer(strategy="median"),
        FunctionTransformer(np.log, feature_names_out="one-to-one"),
        StandardScaler()
    )

cluster_simil = ClusterSimilarity(n_clusters=10, gamma=1, random_state=42)
default_num_pipeline = make_pipeline(
    SimpleImputer(strategy="median"),
    StandardScaler()
)

preprocessing = ColumnTransformer([
    ("bedrooms", ratio_pipeline(), ["total_bedrooms", "total_rooms"]), 
    ("rooms_per_house", ratio_pipeline(), ["total_rooms", "households"]),
    ("people_per_house", ratio_pipeline(), ["population", "households"]),
    ("log", log_pipeline, ["total_bedrooms", "total_rooms", "population", "households", "median_income"]),
    ("geo", cluster_simil, ["latitude", "longitude"]),
    ("cat", cat_pipeline, make_column_selector(dtype_include=object))
],
remainder=default_num_pipeline
)

In [55]:
housing = pd.read_csv("data/housing_train_prepped.csv", index_col=0)
housing_labels = pd.read_csv("data/housing_train_labels.csv", index_col=0)
housing.head()

bedrooms__ratio  rooms_per_house__ratio  people_per_house__ratio  \
13096         1.846624               -0.866027                -0.330204   
14973        -0.508121                0.024550                -0.253616   
3785         -0.202155               -0.041193                -0.051041   
14689        -0.149006               -0.034858                -0.141475   
20507         0.963208               -0.666554                -0.306148   

       log__total_bedrooms  log__total_rooms  log__population  \
13096             1.324114          0.637892         0.456906   
14973            -0.252671         -0.063576        -0.711654   
3785             -0.925266         -0.859927        -0.941997   
14689             0.952773          0.943475         0.670700   
20507             1.437622          1.003590         0.719093   

       log__households  log__median_income  geo__Cluster 0 similarity  \
13096         1.310369           -1.071522               4.581829e-01   
14973        -0.142030            1.194712               6.511495e-10   
3785         -0.913030           -0.756981               3.432506e-01   
14689         0.925373           -0.912253               2.244844e-15   
20507         1.481464            0.034537               1.090228e-11   

       geo__Cluster 1 similarity  ...  geo__Cluster 6 similarity  \
13096               1.241847e-14  ...               8.489216e-04   
14973               9.579596e-01  ...               5.614049e-27   
3785                4.261141e-15  ...               5.641131e-03   
14689               2.704823e-01  ...               5.913326e-35   
20507               9.422206e-01  ...               5.421817e-30   

       geo__Cluster 7 similarity  geo__Cluster 8 similarity  \
13096               9.770322e-01               2.382191e-08   
14973               1.260964e-13               1.103491e-01   
3785                7.303265e-01               2.508224e-08   
14689               5.201263e-20               1.712982e-03   
20507               1.048030e-15               2.568824e-02   

       geo__Cluster 9 similarity  cat__ocean_proximity_<1H OCEAN  \
13096               3.819126e-18                             0.0   
14973               3.547610e-01                             1.0   
3785                2.669659e-18                             0.0   
14689               8.874598e-01                             0.0   
20507               5.279506e-01                             0.0   

       cat__ocean_proximity_INLAND  cat__ocean_proximity_ISLAND  \
13096                          0.0                          0.0   
14973                          0.0                          0.0   
3785                           1.0                          0.0   
14689                          1.0                          0.0   
20507                          0.0                          0.0   

       cat__ocean_proximity_NEAR BAY  cat__ocean_proximity_NEAR OCEAN  \
13096                            1.0                              0.0   
14973                            0.0                              0.0   
3785                             0.0                              0.0   
14689                            0.0                              0.0   
20507                            0.0                              1.0   

       remainder__housing_median_age  
13096                       1.861119  
14973                       0.907630  
3785                        0.351428  
14689                      -0.919891  
20507                       0.589800  

[5 rows x 24 columns]

## Train and Evaluate

#### With Linear Regression

In [56]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(housing, housing_labels)

housing_predictions = lin_reg.predict(housing)
housing_predictions[:5].round(-2)

array([[246000.],
       [372700.],
       [135700.],
       [ 91400.],
       [330900.]])

In [57]:
housing_labels.iloc[:5].values

array([[458300.],
       [483800.],
       [101700.],
       [ 96100.],
       [361800.]])

In [58]:
from sklearn.metrics import root_mean_squared_error

lin_rmse = root_mean_squared_error(housing_labels, housing_predictions)
lin_rmse

68972.88910758459

#### With Decision Tree Regressor

In [59]:
from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor(random_state=42)
tree_reg.fit(housing, housing_labels)

housing_predictions = tree_reg.predict(housing)
housing_predictions[:5].round(2)

array([458300., 483800., 101700.,  96100., 361800.])

In [60]:
housing_labels[:5].values

array([[458300.],
       [483800.],
       [101700.],
       [ 96100.],
       [361800.]])

In [61]:
tree_rmse = root_mean_squared_error(housing_labels, housing_predictions)
tree_rmse # Model Overfits!

0.0

## Cross Validation

In [62]:
from sklearn.model_selection import cross_val_score

tree_rmse = -cross_val_score(tree_reg, housing, housing_labels, 
                            scoring="neg_root_mean_squared_error", cv=10)

pd.Series(tree_rmse).describe()

count       10.000000
mean     66149.463525
std       2505.997238
min      62602.424703
25%      63914.082682
50%      66248.434408
75%      68107.671276
max      69853.960730
dtype: float64

#### Attempt with Random Forest Regressor

In [63]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import make_pipeline

forest_reg = RandomForestRegressor(random_state=42)
forest_rmses = -cross_val_score(forest_reg, housing, housing_labels["median_house_value"], scoring="neg_root_mean_squared_error", cv=10)

In [64]:
pd.Series(forest_rmses).describe()

count       10.000000
mean     47174.587364
std        996.823918
min      45617.905147
25%      46559.165989
50%      47225.189327
75%      47495.894845
max      49392.754151
dtype: float64

## Fine Tune Hyperparams